### PR TITLE
Add CMake build process

### PR DESCRIPTION
**Pull request by jatkinson1000**
This PR adds a cmake build process to MiMA.
It will provide an alternative method for building that should be system independent.

`CMakeLists` files are added to directories that are otherwise ignores by other build processes.

Tasks:
- [X] Working cmake build on local system
- [x] Test build on other systems
    - [X] Test on CSD3 (Cambridge, UK) by Jack Atkinson
    - [X] Test on NYU by Minah Yang
    - [x] Test on Stanford by Laura Mansfield
- [x] Add documentation instructions on how to build using CMake
- [x] Test build instructions and amend as appropriate.

For the benefit of @mjucker there has been some restructuring and cleaning of git repositories within ICCS/DataWave to reduce complexity. The ICCS work has been transferred to the DataWave fork of MiMA and the ICCS fork will shortly be closed. This PR replaces #33 exactly. Once I have copied comments across I will close #33 in favour of this.

### CODE REVIEW

**Comment by jatkinson1000** [comment]
Great stuff, very useful. I think the documentation instructions are critical to pull this into the main repository.

_Originally posted by @mjucker in https://github.com/mjucker/MiMA/issues/33#issuecomment-1450992493_

**Comment by jatkinson1000** [comment]
Thanks, and I agree.
Once I've added this and Laura tests on Sherlock I'll remove the draft tag and request review from you.

_Originally posted by @jatkinson1000 in https://github.com/mjucker/MiMA/issues/33#issuecomment-1451489458_

**Comment by jatkinson1000** [comment]
Update: Issues with building on Sherlock via CMake during testing by @lm2612

Output is as follows:
```
Building Fortran object CMakeFiles/mima.x.dir/src/coupler/simple_surface.f90.o
/scratch/users/lauraman/cmake_test/MiMA/src/coupler/simple_surface.f90(39): error #6580: Name in only-list does not exist or is not accessible.  [GRID_DOMAIN]
use transforms_mod, only: get_grid_boundaries, grid_domain,get_grid_domain, get_lon_max, get_lat_max  
------------------------------------------------^
compilation aborted for /scratch/users/lauraman/cmake_test/MiMA/src/coupler/simple_surface.f90 (code 1)
make[2]: *** [CMakeFiles/mima.x.dir/src/coupler/simple_surface.f90.o] Error 1
make[1]: *** [CMakeFiles/mima.x.dir/all] Error 2
make: *** [all] Error 2
```

Not immediately clear what the issue is and we are unable to replicate on CSD3.
To further confuse things the mkmf build process _does_ work on Sherlock.
May need a sit-down meeting with @SimonClifford @jatkinson1000 and @lm2612 to debug.

**Comment by dorchard** [comment]
Do we expect this to work with both `mpich` and `openmpi`?

**Comment by lm2612** [comment]
Apologies for the delay, I've just managed to get this working on sherlock. I think we have solved some of the sherlock issues with modules - now I can successfully compile the old version (with the unused variables in `coupler/simple_surface.f90`). This version compiles and runs with both `mpich` or `openmpi` for me on sherlock.

**Comment by jatkinson1000** [comment]
Oh, amazing!
Can you describe what changes you had to make?

I'll now tick off Sherlock above and open for review from Martin! :rocket:

**Comment by lm2612** [comment]
The current version compiled with the same default modules I was trying previously: 
image
but both versions work with these modules ("cees-beta" is a sherlock environment, I think its best for sherlock users to go with this option)
image
I had tried something similar to the latter previously and I still don't know exactly why it wasn't working, but I think `mpich-cees-beta/3.3.2-ndjfz` wasn't loading properly as I was missing `gcc-cees-beta/11.2.0-3zp2o`, so it could something like that?

**Comment by jatkinson1000** [comment]
As discussed we are now happy that this build process is robust having been tested on multiple systems. Therefore I'm moving out of draft for review by @mjucker

**Comment by mjucker** [comment]
This is fantastic work, ; thanks veryone for your efforts and for allowing me to pull this into the main MiMA code!

**Comment by dorchard** [comment]
Thanks @mjucker!

**Pull request merged**
